name: Extract issue numbers

author: steven.jeong

description: Extract issue numbers from commit list

inputs:
  githubToken:
    description: Github Token that has access to `repo`
    required: true

runs:
  using: 'node16'
  main: 'lib/index.js'

branding:
  icon: 'list'
  color: 'white'
